update edit tests, fix checkstyle and bugs
AY2324S1-CS2103T-T09-3/tp pull request #80
Opened 2023-10-15 05:45 UTC by tanveersingh10

2023-10-15 06:07 UTC, cmHuang777 requested changes
Overall looks good, just some nits on a test case deleted.

2023-10-15 06:07 UTC, cmHuang777 commented on src/test/java/seedu/address/logic/commands/EditCommandTest.java
> -    public void execute_duplicatePersonFilteredList_failure() {
Are there any tests to replace editing other persons into duplicates?

2023-10-15 07:40 UTC, chonguschonguschongus reviewed
LGTM. Overall code quality is great except the slightly longer execute() method for EditCommand.

2023-10-15 07:40 UTC, chonguschonguschongus commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +        if (personToEdit instanceof Patient) {
Possible to extract out this part of the function? Think the execute is a bit too long and will cost us readability.

2023-10-16 06:26 UTC, cmHuang777 approved these changes

2023-10-16 06:27 UTC, cmHuang777 approved these changes
We will merge first then fix the tests in a separate pr

2023-10-16 06:29 UTC, Mohammed-Faizzzz approved these changes
We'll merge this first, and introduce more testcases ASAP.

2023-10-16 06:50 UTC, merged